import ollama



MODEL_NAME = "llama3.2:3b"
# MODEL_NAME = "llama3.1:8b"



# LLM FUNCTION
def ask_llm(prompt: str) -> str:
    """
    Send a prompt to the local LLM using Ollama.

    Parameters
    ----------
    prompt : str
        Prompt generated from the object detection module.

    Returns
    -------
    str
        Response generated by the LLM.
    """

    system_prompt = """
You are VisionReasoner, an AI assistant that answers questions about images
using the output of an object detection model.

Your task is to provide natural, fluent and conversational answers.

Rules:

- Answer in normal English, like ChatGPT.
- Write in complete sentences.
- Do not use headings such as "Observed facts", "Reasoning", or "Limitations".
- Never invent objects that were not detected.
You may make reasonable hypotheses, but always distinguish between observations and assumptions.

Use expressions such as:

- It appears...
- It may suggest...
- It is possible that...
- Based on the detected objects...
- However, this cannot be confirmed from object detection alone.
- If there is insufficient information, explain why in a natural way.
- Keep the answer concise unless the user asks for more detail.
"""

    try:

        response = ollama.chat(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        return response["message"]["content"]

    except Exception as e:

        return f"LLM Error:\n{e}"


